### ISSUE TITLE
Merge with Formatting.jl or make its C style more explicit?

### ISSUE THREAD

**Issue by tonyhffong** [tonyhffong/NumFormat.jl#1]
https://github.com/JuliaLang/METADATA.jl/pull/1764#comments

cc @kmsquire, @lindahua

**Comment by lindahua** [comment]
I think they can be merged, after some discussions.

**Comment by tonyhffong** [comment]
@lindahua and I agreed on merging. Here's my PR: https://github.com/lindahua/Formatting.jl/pull/1

**Comment by lindahua** [comment]
I have merged your PR.
