### ISSUE TITLE
broken on Julia 0.4.3

### ISSUE THREAD

**Issue by lewisl** [tonyhffong/NumFormat.jl#2]
Oh, well....

**Comment by tonyhffong** [comment]
It's a deprecated package. all features are transferred into Formatting.jl.

**Comment by lewisl** [comment]
Yup. I switched.

On Sat, Apr 30, 2016 at 1:36 PM -0700, "tonyhffong" <notifications@github.com<mailto:notifications@github.com>> wrote:

Closed #2https://github.com/tonyhffong/NumFormat.jl/issues/2.

##
